server:
  port: 8762

mybatis:
  mapper-locations: static/mapping/*.xml
spring:
  application:
    name: service-hi
  datasource:
    url: jdbc:mysql://192.168.1.22:3306/test?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jackson:
    time-zone: GMT+8

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

